export type CatalogProductFixture = Readonly<{
  name: string;
  description: string;
  price: number;
  category: "Accessories" | "Monitors";
  imageUrl: string;
  stockCount: number;
  discountPercent: number;
  isNew: boolean;
  isBestSeller: boolean;
  isFeatured: boolean;
  ratings: readonly number[];
  strengths: readonly string[];
  concerns: readonly string[];
}>;

const product = (fixture: CatalogProductFixture): CatalogProductFixture =>
  fixture;

export const catalogProductFixtures = [
  product({
    name: "Mechanical Keyboard",
    description: "RGB mechanical keyboard with tactile blue switches",
    price: 89.99,
    category: "Accessories",
    imageUrl: "/products/mechanical-keyboard.png",
    stockCount: 20,
    discountPercent: 10,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    ratings: [5, 4, 5, 3, 5, 4, 2, 5, 4, 5, 3, 4, 5, 4, 5, 4],
    strengths: [
      "the tactile switches feel crisp and consistent",
      "the frame stays planted during fast typing",
      "the lighting remains tasteful at lower brightness",
      "every key registers quickly and reliably",
    ],
    concerns: [
      "the switches are loud in a shared room",
      "the software occasionally forgets saved profiles",
      "a wrist rest would improve longer sessions",
    ],
  }),
  product({
    name: "Gaming Mouse",
    description: "Wireless gaming mouse with precise adjustable tracking",
    price: 59.99,
    category: "Accessories",
    imageUrl: "/products/gaming-mouse.png",
    stockCount: 35,
    discountPercent: 15,
    isNew: false,
    isBestSeller: false,
    isFeatured: true,
    ratings: [5, 4, 5, 4, 3, 5, 4, 2, 5, 4, 3, 4, 5, 4],
    strengths: [
      "tracking stays precise during quick movements",
      "the wireless connection feels immediate",
      "the shape remains comfortable through long sessions",
      "battery life covers a full workweek",
    ],
    concerns: [
      "the shell feels narrow in larger hands",
      "the scroll click is louder than the main buttons",
      "the side buttons are easy to press accidentally",
    ],
  }),
  product({
    name: "27-inch Monitor",
    description: "144Hz IPS monitor for fluid gaming and everyday work",
    price: 299.99,
    category: "Monitors",
    imageUrl: "/products/27-inch-monitor.png",
    stockCount: 12,
    discountPercent: 20,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    ratings: [5, 4, 5, 4, 3, 5, 4, 2, 5, 4, 4, 5, 3, 4, 5, 4, 5],
    strengths: [
      "motion looks exceptionally smooth at 144Hz",
      "text remains sharp throughout the workday",
      "colors stay consistent when viewed off-center",
      "the slim bezels suit a dual-monitor setup",
    ],
    concerns: [
      "the stand offers limited height adjustment",
      "dark scenes reveal some backlight glow",
      "the on-screen controls take time to learn",
    ],
  }),
  product({
    name: "Low-Profile Wireless Keyboard",
    description: "Slim 75% wireless keyboard with quiet mechanical switches",
    price: 119.99,
    category: "Accessories",
    imageUrl: "/products/low-profile-wireless-keyboard.png",
    stockCount: 28,
    discountPercent: 0,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    ratings: [5, 4, 5, 5, 3, 4, 5, 4, 2, 5, 4, 5, 4, 5, 4, 5],
    strengths: [
      "the low-profile switches feel quick without becoming tiring",
      "switching between paired devices takes only a moment",
      "the compact layout preserves the keys I use most",
      "the aluminum frame feels unusually solid",
    ],
    concerns: [
      "the shortened right shift key requires adjustment",
      "the backlight reduces battery life noticeably",
      "replacement keycaps are difficult to find",
    ],
  }),
  product({
    name: "Ergonomic Wireless Mouse",
    description: "Sculpted vertical mouse designed for relaxed all-day control",
    price: 74.99,
    category: "Accessories",
    imageUrl: "/products/ergonomic-wireless-mouse.png",
    stockCount: 24,
    discountPercent: 10,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    ratings: [4, 5, 3, 5, 4, 4, 5, 2, 4, 5, 3, 4, 5, 5],
    strengths: [
      "the vertical shape keeps my wrist relaxed",
      "the metal wheel scrolls with precise steps",
      "the sensor tracks reliably on several surfaces",
      "the side buttons sit naturally beneath my thumb",
    ],
    concerns: [
      "the tall shape takes several days to learn",
      "the shell is less suitable for smaller hands",
      "the receiver has no storage compartment",
    ],
  }),
  product({
    name: "7-Port USB-C Hub",
    description: "Compact aluminum hub with HDMI, USB, and card connectivity",
    price: 69.99,
    category: "Accessories",
    imageUrl: "/products/usb-c-hub.png",
    stockCount: 42,
    discountPercent: 15,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    ratings: [4, 3, 5, 4, 2, 4, 5, 3, 4, 2, 5, 4, 3, 4, 4],
    strengths: [
      "all seven ports remain useful without making the hub bulky",
      "the HDMI output stays stable",
      "the card readers transfer large folders quickly",
      "the aluminum enclosure feels sturdy",
    ],
    concerns: [
      "the integrated cable is shorter than I would like",
      "the enclosure becomes warm during transfers",
      "wide USB plugs compete for space",
      "power delivery falls below the maximum",
    ],
  }),
  product({
    name: "Adjustable Laptop Stand",
    description: "Ventilated aluminum stand with flexible height and angle",
    price: 54.99,
    category: "Accessories",
    imageUrl: "/products/aluminum-laptop-stand.png",
    stockCount: 31,
    discountPercent: 0,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    ratings: [5, 4, 5, 5, 4, 3, 5, 4, 5, 4, 5, 4, 5],
    strengths: [
      "the hinges hold position without wobble",
      "the open design leaves room for airflow",
      "the silicone pads grip without marking",
      "the height brings the camera to eye level",
    ],
    concerns: [
      "adjustment requires a firm two-handed grip",
      "the stand is heavy for travel",
      "the front hooks feel prominent on thin laptops",
    ],
  }),
  product({
    name: "4K Webcam",
    description: "Sharp 4K webcam with autofocus and a physical privacy cover",
    price: 129.99,
    category: "Accessories",
    imageUrl: "/products/4k-webcam.png",
    stockCount: 18,
    discountPercent: 10,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    ratings: [4, 5, 3, 4, 2, 5, 4, 3, 5, 1, 4, 3, 5, 4, 2, 4, 5],
    strengths: [
      "the image stays detailed after cropping",
      "autofocus follows movement without pulsing",
      "the privacy cover closes securely",
      "skin tones look natural in window light",
    ],
    concerns: [
      "low-light footage develops visible grain",
      "the clip feels loose on thin monitors",
      "the microphones sound distant",
      "the companion software is slow",
    ],
  }),
  product({
    name: "USB Condenser Microphone",
    description:
      "Compact cardioid microphone for calls, streaming, and recording",
    price: 109.99,
    category: "Accessories",
    imageUrl: "/products/usb-condenser-microphone.png",
    stockCount: 16,
    discountPercent: 0,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    ratings: [5, 4, 5, 3, 5, 4, 5, 2, 4, 5, 4, 3, 5, 5],
    strengths: [
      "voices sound clear without much processing",
      "the gain control is easy to adjust",
      "the weighted stand stays steady",
      "keyboard noise is rejected surprisingly well",
    ],
    concerns: [
      "the included stand sits rather low",
      "plosive sounds need a pop filter",
      "the mute indicator is hard to see in daylight",
    ],
  }),
  product({
    name: "Noise-Cancelling Headphones",
    description:
      "Comfortable wireless headphones with adaptive noise cancellation",
    price: 229.99,
    category: "Accessories",
    imageUrl: "/products/noise-cancelling-headphones.png",
    stockCount: 22,
    discountPercent: 15,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    ratings: [5, 5, 4, 5, 3, 5, 4, 5, 4, 2, 5, 5, 4, 5, 4, 5],
    strengths: [
      "noise cancellation quiets steady office sounds",
      "the cushions remain comfortable for hours",
      "battery life lasts through multiple workdays",
      "music retains detail at low volume",
    ],
    concerns: [
      "transparency mode adds a faint hiss",
      "the headband feels firm at first",
      "multipoint switching occasionally pauses",
    ],
  }),
  product({
    name: "Desktop Studio Speakers",
    description:
      "Compact powered speakers tuned for balanced near-field listening",
    price: 179.99,
    category: "Accessories",
    imageUrl: "/products/desktop-speakers.png",
    stockCount: 14,
    discountPercent: 5,
    isNew: false,
    isBestSeller: false,
    isFeatured: true,
    ratings: [4, 5, 3, 4, 5, 2, 4, 3, 5, 4, 2, 5, 3, 4, 4],
    strengths: [
      "voices and instruments sound balanced",
      "the compact cabinets save desk space",
      "the volume control is precise",
      "the stereo image feels impressively wide",
    ],
    concerns: [
      "deep bass loses weight at high volume",
      "the connecting cable limits placement",
      "a faint hiss is audible at idle",
      "the finish collects fingerprints",
    ],
  }),
  product({
    name: "Wireless Charging Pad",
    description: "Slim 15W charging pad with a cool-touch aluminum frame",
    price: 39.99,
    category: "Accessories",
    imageUrl: "/products/wireless-charging-pad.png",
    stockCount: 50,
    discountPercent: 20,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    ratings: [3, 4, 2, 3, 1, 4, 3, 2, 4, 3, 1, 2, 3],
    strengths: [
      "the low profile keeps my desk uncluttered",
      "the rubber surface prevents sliding",
      "the indicator stays dim at night",
    ],
    concerns: [
      "charging slows through thick cases",
      "the phone must be positioned precisely",
      "the pad becomes warmer than expected",
      "a power adapter is not included",
    ],
  }),
  product({
    name: "Monitor Light Bar",
    description: "Adjustable screen light with wireless brightness controls",
    price: 89.99,
    category: "Accessories",
    imageUrl: "/products/monitor-light-bar.png",
    stockCount: 27,
    discountPercent: 0,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    ratings: [5, 4, 5, 3, 5, 4, 5, 4, 2, 5, 4, 5, 3, 4, 5, 4, 5],
    strengths: [
      "the beam lights my desk without screen glare",
      "the wireless dial is effortless",
      "color temperature covers work and evenings",
      "the mounting clip feels secure",
    ],
    concerns: [
      "the clip does not suit thick monitor backs",
      "the dial requires separate batteries",
      "automatic brightness reacts slowly",
    ],
  }),
  product({
    name: "24-inch Office Monitor",
    description: "Crisp 1080p IPS display with ergonomic height adjustment",
    price: 189.99,
    category: "Monitors",
    imageUrl: "/products/24-inch-office-monitor.png",
    stockCount: 25,
    discountPercent: 10,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    ratings: [4, 5, 4, 3, 5, 4, 2, 4, 5, 3, 4, 5, 4, 5],
    strengths: [
      "text looks crisp at office distance",
      "the stand adjusts through a useful range",
      "colors remain consistent across the panel",
      "the footprint suits a smaller desk",
    ],
    concerns: [
      "the built-in speakers sound thin",
      "the ports omit USB-C",
      "the menu buttons are awkwardly placed",
    ],
  }),
  product({
    name: "32-inch 4K Creator Monitor",
    description: "Color-accurate 4K display with USB-C power delivery",
    price: 549.99,
    category: "Monitors",
    imageUrl: "/products/32-inch-4k-monitor.png",
    stockCount: 10,
    discountPercent: 0,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    ratings: [5, 4, 5, 5, 3, 4, 5, 5, 2, 4, 5, 4, 5, 5, 4],
    strengths: [
      "fine text and photos look exceptionally sharp",
      "the factory color profile is accurate",
      "one USB-C cable handles video and charging",
      "the large canvas makes multitasking natural",
    ],
    concerns: [
      "the stand occupies considerable desk depth",
      "uniformity dips near the lower corners",
      "maximum brightness runs warm",
    ],
  }),
  product({
    name: "34-inch Curved Ultrawide Monitor",
    description:
      "Immersive 1440p ultrawide display with a smooth 165Hz refresh rate",
    price: 699.99,
    category: "Monitors",
    imageUrl: "/products/34-inch-ultrawide-monitor.png",
    stockCount: 8,
    discountPercent: 10,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    ratings: [5, 4, 5, 3, 5, 5, 4, 2, 5, 4, 5, 3, 4, 5, 5, 4],
    strengths: [
      "the wide canvas replaces two monitors cleanly",
      "the curve keeps the edges comfortable to view",
      "motion remains clear at full refresh rate",
      "timelines use the extra width well",
    ],
    concerns: [
      "the stand requires a deep desk",
      "older games leave black side bars",
      "local dimming is basic for the price",
    ],
  }),
  product({
    name: "15.6-inch Portable USB-C Monitor",
    description:
      "Lightweight second screen powered through a single USB-C cable",
    price: 249.99,
    category: "Monitors",
    imageUrl: "/products/portable-usb-c-monitor.png",
    stockCount: 19,
    discountPercent: 5,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    ratings: [4, 3, 5, 2, 4, 3, 1, 5, 4, 2, 3, 4, 5],
    strengths: [
      "one cable carries power and video",
      "the panel travels easily beside my laptop",
      "the cover protects the screen in a bag",
      "text remains clear at recommended scaling",
    ],
    concerns: [
      "the folding stand slips at steep angles",
      "brightness is limited near sunny windows",
      "the side controls are tiny",
      "the included cable is stiff",
    ],
  }),
  product({
    name: "27-inch OLED Gaming Monitor",
    description:
      "240Hz OLED display with deep contrast and near-instant response",
    price: 899.99,
    category: "Monitors",
    imageUrl: "/products/oled-gaming-monitor.png",
    stockCount: 7,
    discountPercent: 0,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    ratings: [5, 5, 4, 5, 5, 3, 5, 4, 5, 2, 5, 5, 4, 5, 5, 4, 5],
    strengths: [
      "dark scenes retain detail with deep blacks",
      "motion at 240Hz looks exceptionally clean",
      "pixel response feels immediate",
      "colors stay rich without losing gradients",
    ],
    concerns: [
      "brightness limiting is visible on white pages",
      "text fringing appears when viewed closely",
      "panel care sometimes starts inconveniently",
    ],
  }),
] as const;
